/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import React from 'react'
import {establishSession,fetchFilterOptions,fetchSessionMetadata,fetchStatus,queryMetrics,subscribe,type DashboardQuery,type FilterOptions,type MetricResult,type SessionPage,type Status} from './api'
import {capacityCountdown} from './capacity'
import {ContextInspector} from './context-inspector'
import {Reviews} from './reviews'
import {shouldReloadForRevision} from './revision'
import {AppShell} from './app-shell'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { Tooltip as UiTooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { AlertTriangle, Info, RefreshCw } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Legend, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from 'recharts'

const keys=['recorded_tokens','recorded_tokens_by_kind','recorded_tokens_over_time','token_composition','top_root_sessions_by_tokens','latest_capacity_observation','capacity_drawdown']
const fallbackKinds:FilterOptions['contributionKinds']=[{value:'user_root_direct',label:'User root'},{value:'descendant',label:'Descendants'},{value:'inspector_review',label:'Inspector Review'},{value:'other_orphan',label:'Other / orphan'}]
type Item={key:string;value:any;fidelity:string;coverage:{fidelity:string;observed:number;eligible:number;reason?:string};indexedCoverage:{indexedStart:string|null;indexedEnd:string|null;completedWatermark:string|null};exclusionReasons:Record<string,number>}
type CapacityPoint={observedAt:string;usedPercent:number}
type CapacitySeries={limitId:string;windowMinutes:number;resetBoundary:string;points:CapacityPoint[]}
type CapacityWindowHistory={limitId:string;windowMinutes:number;dataKey:string;resetBoundaries:Set<string>;points:CapacityPoint[]}
const item=(data:MetricResult|null,key:string)=>data?.results?.find((x:any)=>x.key===key) as unknown as Item|undefined
const number=(value:number|null|undefined)=>value==null?'Unavailable':new Intl.NumberFormat().format(value)
const camel=(value:string)=>value.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase())
const kindColors:Record<string,string>={user_root_direct:'#1e5a50',descendant:'#7da58b',inspector_review:'#d6ad58',other_orphan:'#a97770'}
const compositionColors=['#1e5a50','#7da58b','#d6ad58','#a97770','#87938c']
function diagnostics(status:Status){return JSON.stringify({summary:'Payload-safe Inspector runtime checks.',index:{state:status.index.state,sources:status.index.sourceCount,supported:status.index.supportedSourceCount,unsupported:status.index.unsupportedSourceCount,failed:status.index.failedCount,schemaVersion:status.index.schemaVersion,sourceGroups:status.index.diagnosticGroups},hook:{state:status.hook.state,diagnostics:status.hook.diagnostics}},null,2)}
function buildCapacityHistory(series:CapacitySeries[]){const windowsByKey=new Map<string,CapacityWindowHistory>();series.forEach(item=>{const key=`${item.limitId}\u0000${item.windowMinutes}`,current=windowsByKey.get(key)||{limitId:item.limitId,windowMinutes:item.windowMinutes,dataKey:`capacity${windowsByKey.size}`,resetBoundaries:new Set<string>(),points:[]};current.resetBoundaries.add(item.resetBoundary);current.points.push(...item.points);windowsByKey.set(key,current)});const windows=[...windowsByKey.values()],rows=new Map<number,Record<string,number>>();windows.forEach(window=>window.points.forEach(point=>{const observedAt=new Date(point.observedAt).getTime(),row=rows.get(observedAt)||{observedAt};row[window.dataKey]=point.usedPercent;rows.set(observedAt,row)}));return{windows,rows:[...rows.values()].sort((a,b)=>a.observedAt-b.observedAt)}}

function DashboardSkeleton(){return <section className="grid dashboard-skeleton" aria-busy="true" aria-label="Loading dashboard metrics"><article className="wide"><Skeleton className="skeleton-heading"/><div className="skeleton-split"><div><Skeleton className="skeleton-value"/><Skeleton className="skeleton-bar"/><Skeleton className="skeleton-copy"/></div><div><Skeleton className="skeleton-value"/><Skeleton className="skeleton-bar"/><Skeleton className="skeleton-copy"/></div></div></article><article><Skeleton className="skeleton-heading"/><Skeleton className="skeleton-value"/><Skeleton className="skeleton-bar"/><div className="skeleton-list"><Skeleton/><Skeleton/><Skeleton/></div></article><article className="wide"><Skeleton className="skeleton-heading"/><div className="skeleton-columns">{[46,68,84,38,57,91,64].map((height,index)=><Skeleton key={index} style={{height:`${height}%`}}/>)}</div></article><article><Skeleton className="skeleton-heading"/><div className="skeleton-columns compact">{[78,44,62,31,18].map((height,index)=><Skeleton key={index} style={{height:`${height}%`}}/>)}</div></article><article className="wide"><Skeleton className="skeleton-heading"/><div className="skeleton-table">{[0,1,2,3].map(row=><div key={row}><Skeleton/><Skeleton/><Skeleton/></div>)}</div></article><article className="wide"><Skeleton className="skeleton-heading"/><div className="skeleton-line-chart"><Skeleton/><Skeleton/><Skeleton/><Skeleton/><Skeleton/><Skeleton/></div></article></section>}

export function App(){
  const [status,setStatus]=React.useState<Status|null>(null),[data,setData]=React.useState<MetricResult|null>(null),[sessions,setSessions]=React.useState<SessionPage['items']>([]),[error,setError]=React.useState('')
  const [options,setOptions]=React.useState<FilterOptions>({projects:[],models:[],reasoningEfforts:[],contributionKinds:fallbackKinds})
  const [range,setRange]=React.useState('30'),[project,setProject]=React.useState(''),[model,setModel]=React.useState(''),[reasoning,setReasoning]=React.useState(''),[kind,setKind]=React.useState('')
  const [applied,setApplied]=React.useState<number|null>(null),[available,setAvailable]=React.useState<number|null>(null),[indexing,setIndexing]=React.useState(false),[metricsLoading,setMetricsLoading]=React.useState(false),[sessionsLoading,setSessionsLoading]=React.useState(false),[now,setNow]=React.useState(Date.now()),[coverageOpen,setCoverageOpen]=React.useState(false),[copied,setCopied]=React.useState(false)
  const appliedRef=React.useRef<number|null>(null)
  const datasetEpochRef=React.useRef<string|null>(null)
  const metricsRequestRef=React.useRef(0)
  const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'
  const buildQuery=React.useCallback((revision?:number)=>{const q:DashboardQuery={metricKeys:keys,timezone,grain:range==='all'?'month':Number(range)<=2?'hour':'day',projectIds:project?[project]:undefined,models:model?[model]:undefined,reasoningEfforts:reasoning?[reasoning]:undefined,contributionKinds:kind?[kind]:undefined,requestedRevision:revision};if(range!=='all'){const end=new Date(),start=new Date(end.getTime()-Number(range)*86400000);q.start=start.toISOString();q.end=end.toISOString()}return q},[range,project,model,reasoning,kind,timezone])
  const loadMetrics=React.useCallback(async(revision?:number)=>{const request=++metricsRequestRef.current;setMetricsLoading(true);try{const result=await queryMetrics(buildQuery(revision));if(request===metricsRequestRef.current){setData(result);datasetEpochRef.current=result.datasetEpoch;appliedRef.current=result.appliedRevision;setApplied(result.appliedRevision)}return result}finally{if(request===metricsRequestRef.current)setMetricsLoading(false)}},[buildQuery])
  const refreshStatus=React.useCallback(async()=>{const fresh=await fetchStatus();setStatus(fresh);setIndexing(fresh.index.state==='building'||fresh.index.state==='catching_up');return fresh},[])
  React.useEffect(()=>{let off=()=>{},active=true;establishSession().then(initial=>{if(!active)return;setStatus(initial);datasetEpochRef.current=initial.datasetEpoch;appliedRef.current=initial.appliedRevision;setApplied(initial.appliedRevision);setIndexing(initial.index.state==='building'||initial.index.state==='catching_up');off=subscribe(ev=>{if(ev.event==='revision.available'){if(ev.data.fullRefreshRequired){if(shouldReloadForRevision(datasetEpochRef.current,appliedRef.current,ev.data))location.reload();else void refreshStatus();return}const revision=Number(ev.data.revision);if(Number.isFinite(revision)&&revision>(appliedRef.current??0))setAvailable(current=>Math.max(current??0,revision));void refreshStatus()}else if(ev.event==='status.changed'||ev.event==='sync.progress'){setIndexing(ev.data.state==='scanning'||ev.data.state==='catching_up'||Number(ev.data.queued)>0);void refreshStatus()}});void fetchFilterOptions(initial.appliedRevision).then(catalog=>{if(active)setOptions(catalog)}).catch((e:Error)=>{if(active)setError(e.message)});if(initial.index.state!=='empty'&&initial.process.cliCompatibility==='supported'&&initial.process.pluginVersion)void loadMetrics(initial.appliedRevision).catch((e:Error)=>{if(active)setError(e.message)})}).catch((e:Error)=>{if(active)setError(e.message)});const heartbeat=setInterval(()=>void fetch('/v1/heartbeat',{method:'POST',headers:{'X-Inspector-Origin':location.origin}}),15000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{active=false;clearInterval(heartbeat);clearInterval(clock);off()}},[])
  React.useEffect(()=>{if(applied!=null&&status?.index.state!=='empty'&&status?.process.cliCompatibility==='supported'&&status.process.pluginVersion)void loadMetrics(applied).catch(e=>setError(e.message))},[range,project,model,reasoning,kind])
  React.useEffect(()=>{if(applied==null)return;const rootResult=item(data,'top_root_sessions_by_tokens'),rootIDs=(rootResult?.value||[]).slice(0,10).map((root:any)=>root.rootSessionId);if(rootIDs.length===0){setSessions([]);setSessionsLoading(false);return}let active=true;setSessionsLoading(true);void fetchSessionMetadata(rootIDs,applied).then(page=>{if(active)setSessions(Array.isArray(page.items)?page.items:[])}).catch(()=>{if(active)setSessions([])}).finally(()=>{if(active)setSessionsLoading(false)});return()=>{active=false}},[applied,data])
  const applyAvailable=async()=>{if(available==null)return;const target=available;const [,catalog]=await Promise.all([loadMetrics(target),fetchFilterOptions(target)]);setOptions(catalog);await refreshStatus();setAvailable(current=>(appliedRef.current??0)>=target&&!(current!=null&&current>target)?null:current)}
  if(error)return <main className="startup-failure"><p className="startup-kicker">Codex Inspector</p><section className="error"><h1>Local server unavailable</h1><p>{error}</p><p className="startup-next-step">Start or reopen the local server:</p><code className="startup-command">codex-inspector open</code></section></main>
  if(!status)return <main><h1>Codex Inspector</h1><p>Connecting to the local Inspector server…</p></main>
  const setup=!status.process.pluginVersion||status.process.cliCompatibility==='unknown',incompatible=status.process.cliCompatibility==='unsupported',empty=status.index.state==='empty'&&!data,total=item(data,'recorded_tokens'),byKind=item(data,'recorded_tokens_by_kind'),composition=item(data,'token_composition'),overTime=item(data,'recorded_tokens_over_time'),roots=item(data,'top_root_sessions_by_tokens'),latest=item(data,'latest_capacity_observation'),drawdown=item(data,'capacity_drawdown')
  const partial=!!data&&(data.coverage.fidelity!=='exact'||data.coverage.observed<data.coverage.eligible||status.index.unsupportedSourceCount>0||status.index.failedCount>0||indexing)
  const capacityWindows=(latest?.value||[]) as any[],kinds=options.contributionKinds.length?options.contributionKinds:fallbackKinds
  if(location.pathname.startsWith('/context')&&!setup&&!incompatible)return <AppShell status={status}><ContextInspector revision={applied??status.appliedRevision} available={available} onApply={applyAvailable}/></AppShell>
  if(location.pathname.startsWith('/reviews')&&!setup&&!incompatible)return <AppShell status={status}><Reviews revision={applied??status.appliedRevision} projects={options.projects}/></AppShell>
  const usageChart=(overTime?.value||[]).map((bucket:any)=>({bucket:new Date(bucket.bucketStart).toLocaleDateString(undefined,{month:'short',day:'numeric'}),user_root_direct:bucket.byKind.userRootDirect||0,descendant:bucket.byKind.descendant||0,inspector_review:bucket.byKind.inspectorReview||0,other_orphan:bucket.byKind.otherOrphan||0}))
  const totalByKind=Object.fromEntries(kinds.map(x=>[x.value,byKind?.value?.[camel(x.value)]||0]))
  const compositionChart=composition?[{name:'Uncached',fullName:'Uncached input',value:composition.value.uncachedInput||0},{name:'Cached',fullName:'Cached input',value:composition.value.cachedInput||0},{name:'Output',fullName:'Visible output',value:composition.value.visibleOutput||0},{name:'Reasoning',fullName:'Reasoning output',value:composition.value.reasoningOutput||0},{name:'Residual',fullName:'Residual',value:composition.value.residual||0}]:[]
  const capacitySeries=(drawdown?.value||[]) as CapacitySeries[],{windows:capacityHistory,rows:capacityChart}=buildCapacityHistory(capacitySeries),capacityColors=['#a64032','#1e5a50','#d0963f','#53709a','#8b5f94','#697744']
  const sessionByID=new Map(sessions.map(session=>[session.sessionId,session])),maxSessionTokens=Math.max(1,...((roots?.value||[]).map((root:any)=>root.inclusiveTokens||0)))
  const coverageSummary = partial ? `${data?.coverage.observed} of ${data?.coverage.eligible} eligible turns recorded. ${status.index.unsupportedSourceCount} unsupported sources; ${status.index.failedCount} failed.` : 'Coverage is exact for this snapshot.'
  const coverageDetailsSheet = <Sheet open={coverageOpen} onOpenChange={setCoverageOpen}><SheetContent><SheetHeader><SheetTitle>Coverage details</SheetTitle><SheetDescription>Inspector never fills gaps with estimates.</SheetDescription></SheetHeader><div className="coverage-details"><dl><dt>Observed eligible turns</dt><dd>{data?.coverage.observed} / {data?.coverage.eligible}</dd><dt>Supported sources</dt><dd>{status.index.supportedSourceCount}</dd><dt>Unsupported sources</dt><dd>{status.index.unsupportedSourceCount}</dd><dt>Failed sources</dt><dd>{status.index.failedCount}</dd><dt>Incomplete active tails</dt><dd>{status.index.pendingTailCount}</dd><dt>Rebuild required</dt><dd>{status.index.requiresRebuildCount}</dd></dl>{status.index.diagnosticGroups.length?<section className="diagnostic-groups" aria-labelledby="coverage-source-groups"><h3 id="coverage-source-groups">Why sources are limited</h3>{status.index.diagnosticGroups.map((group,index)=><article key={`${group.state}-${group.reason}-${group.detectedVersion}-${index}`}><div><Badge variant={group.state==='failed'?'destructive':'secondary'}>{group.state.replaceAll('_',' ')}</Badge><strong>{group.count} source{group.count===1?'':'s'} · Codex {group.detectedVersion}</strong></div><code>{group.reason}</code><p>{group.remediation}</p></article>)}</section>:<p>No unsupported or failed cohorts were recorded for this snapshot.</p>}</div></SheetContent></Sheet>
  return <AppShell status={status}><section className="dashboard-page"><header><div><span className="eyebrow">LOCAL OBSERVABILITY</span><h1>Token &amp; Capacity</h1></div><div className="dashboard-status"><Badge variant="outline">Snapshot r{applied??status.appliedRevision}</Badge><Badge variant={indexing?'secondary':'outline'}>{indexing?'Indexing':status.index.state}</Badge>{partial&&<TooltipProvider><UiTooltip><TooltipTrigger asChild><Button className="coverage-pill" variant="outline" size="xs" onClick={()=>setCoverageOpen(true)}><AlertTriangle aria-hidden="true" /><span>Partial coverage</span><span className="sr-only">Partial recorded coverage</span><span className="sr-only">Coverage details</span><Info aria-hidden="true" /></Button></TooltipTrigger><TooltipContent className="coverage-tooltip">{coverageSummary}</TooltipContent></UiTooltip></TooltipProvider>}{coverageDetailsSheet}{available!=null&&available!==applied&&<Button className="new-data" size="xs" variant="outline" onClick={()=>void applyAvailable()}><RefreshCw aria-hidden="true" /> New data available — apply</Button>}</div></header>
    {setup?<section className="error"><h2>Finish Inspector setup</h2><p>Install and enable the matching plugin, then review its seven hooks.</p></section>:incompatible?<section className="error"><h2>Inspector versions are incompatible</h2><p>The installed host, plugin, or source format is outside the supported demo contract.</p></section>:empty?<section className="empty"><h2>Ready for your first sync</h2><p>No recorded usage yet. Sync supported Codex rollouts to populate this view.</p><Button onClick={()=>{setIndexing(true);void fetch('/v1/sync',{method:'POST',headers:{'content-type':'application/json'},body:'{"mode":"background"}'})}}>Start sync</Button></section>:<>
      <section className="filters" aria-label="Dashboard filters"><label>Time<select value={range} onChange={e=>setRange(e.target.value)}><option value="2">48 hours</option><option value="7">7 days</option><option value="30">30 days</option><option value="all">All indexed</option></select></label><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">All projects</option>{options.projects.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)}><option value="">All models</option>{options.models.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Reasoning<select value={reasoning} onChange={e=>setReasoning(e.target.value)}><option value="">All levels</option>{options.reasoningEfforts.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Contribution<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">All kinds</option>{kinds.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></section>
      {metricsLoading&&data&&<div className="dashboard-refresh-indicator" role="status"><span aria-hidden="true"/>Refreshing dashboard metrics…</div>}{metricsLoading&&!data?<DashboardSkeleton/>:<section className={`grid${metricsLoading?' is-refreshing':''}`} aria-busy={metricsLoading}><article className="wide"><h2>Current recorded utilization limit</h2>{capacityWindows.length?<div className="capacity-cards">{capacityWindows.map((capacity:any)=>{const capacityStale=now>=new Date(capacity.resetsAt).getTime(),remaining=Math.max(0,100-capacity.usedPercent);return <section key={`${capacity.limitId}-${capacity.windowMinutes}`}><div><Badge variant="outline">{capacity.windowMinutes} minute window</Badge><span>{capacity.limitId}</span></div><strong className="hero">{capacity.usedPercent}% used</strong><div className="metric-bar capacity-bar" role="img" aria-label={`${capacity.usedPercent} percent of the recorded ${capacity.windowMinutes} minute limit used`}><ResponsiveContainer width="100%" height={18}><BarChart layout="vertical" data={[{name:'Utilization',used:capacity.usedPercent,remaining}]} margin={{top:0,right:0,bottom:0,left:0}}><XAxis type="number" domain={[0,100]} hide/><YAxis type="category" dataKey="name" hide/><Bar dataKey="used" stackId="limit" fill="#a64032" isAnimationActive={false}/><Bar dataKey="remaining" stackId="limit" fill="#e4e0d5" isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p>{capacity.remainingPercent==null?`${remaining}% remaining (derived)`: `${capacity.remainingPercent}% remaining (recorded)`}</p><p>Recorded {new Date(capacity.observedAt).toLocaleString()} · resets locally {new Date(capacity.resetsAt).toLocaleString()} · {capacityCountdown(capacity.resetsAt,now)}</p>{(capacityStale||latest?.coverage.fidelity!=='exact')&&<span className="stale">{capacityStale?'Stale recorded observation':'Partial capacity coverage'}</span>}</section>})}</div>:<p>Unavailable — {latest?.coverage.reason||'no supported capacity observation was recorded'}.</p>}<small>Account-wide point-in-time source observations. Windows are kept separate and are not inferred from local tokens or changed by project/model filters.</small></article>
      <article><h2>Total recorded tokens</h2>{total?.coverage.fidelity==='unavailable'?<><strong className="hero">Unavailable</strong><p>{total.coverage.reason}</p></>:<><strong className="hero">{number(total?.value)}</strong>{byKind&&<div className="metric-bar token-total-bar" role="img" aria-label={`Recorded tokens by contribution: ${kinds.map(x=>`${x.label} ${number(totalByKind[x.value])}`).join(', ')}`}><ResponsiveContainer width="100%" height={18}><BarChart layout="vertical" data={[{name:'Tokens',...totalByKind}]} margin={{top:0,right:0,bottom:0,left:0}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" hide/>{kinds.map(x=><Bar key={x.value} dataKey={x.value} stackId="tokens" fill={kindColors[x.value]} isAnimationActive={false}/>)}</BarChart></ResponsiveContainer></div>}</>}<div className="legend token-legend">{byKind&&kinds.map(x=><span key={x.value}><i style={{background:kindColors[x.value]}}/>{x.label}: {number(byKind.value[camel(x.value)])}</span>)}</div></article>
      <article className="wide"><h2>Recorded usage over time</h2><div className="chart-frame" aria-label="Stacked token contribution chart"><ResponsiveContainer width="100%" height={260}><BarChart data={usageChart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="bucket"/><YAxis/><ChartTooltip/><Legend/><Bar dataKey="user_root_direct" name="User root direct" stackId="usage" fill="#1e5a50"/><Bar dataKey="descendant" name="Descendant" stackId="usage" fill="#7da58b"/><Bar dataKey="inspector_review" name="Inspector Review" stackId="usage" fill="#d6ad58"/><Bar dataKey="other_orphan" name="Other / orphan" stackId="usage" fill="#a97770"/></BarChart></ResponsiveContainer></div><p className="chart-summary">{usageChart.length ? `${usageChart.length} recorded time buckets shown with an accessible legend and tooltip.` : 'No recorded usage falls within this range.'}</p></article>
      <article><h2>Token composition</h2>{composition?.coverage.fidelity==='unavailable'?<p>Unavailable — {composition.coverage.reason}.</p>:composition&&<><div className="composition-chart" role="img" aria-label={`Token composition: ${compositionChart.map(entry=>`${entry.fullName} ${number(entry.value)}`).join(', ')}`}><ResponsiveContainer width="100%" height={230}><BarChart data={compositionChart} margin={{top:16,right:4,bottom:4,left:4}}><CartesianGrid vertical={false} stroke="#e1dccf"/><XAxis dataKey="name" tick={{fontSize:10,fill:'#69736d'}} tickLine={false} axisLine={false}/><YAxis hide/><ChartTooltip formatter={(value,name,props)=>[number(Number(value)),props.payload.fullName]}/><Bar dataKey="value" radius={[3,3,0,0]}>{compositionChart.map((entry,index)=><Cell key={entry.name} fill={compositionColors[index]}/>)}</Bar></BarChart></ResponsiveContainer></div>{composition.coverage.fidelity!=='exact'&&<p className="stale">Partial: {composition.coverage.observed} of {composition.coverage.eligible} turns</p>}</>}<small>Components are mutually exclusive; cached input and reasoning output are not counted twice.</small></article>
      <article className="wide"><h2>Most token-intensive sessions</h2>{sessionsLoading&&<div className="session-loading-indicator" role="status"><span aria-hidden="true"/>Loading session details…</div>}<div className="session-table" role="table" aria-label="Most token-intensive root sessions" aria-busy={sessionsLoading}><div role="row" className="session-table-head"><span role="columnheader">Session</span><span role="columnheader">Project / start</span><span role="columnheader">Recorded tokens</span><span role="columnheader">Actions</span></div>{(roots?.value||[]).slice(0,10).map((r:any)=>{const session=sessionByID.get(r.rootSessionId);const title=session?.title?.trim()||[session?.project?.split('/').filter(Boolean).at(-1),session?.startedAt&&new Date(session.startedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})].filter(Boolean).join(' · ')||'Recorded Codex session',projectLabel=session?.project||'Project unavailable';return <div role="row" key={r.rootSessionId}><div role="cell"><a href={`/context/${encodeURIComponent(r.rootSessionId)}`}><strong>{title}</strong><small>{session?.completedTurns??'—'} completed turns</small></a></div><span role="cell" className="session-project-cell" title={projectLabel}>{projectLabel}<small>{session?.startedAt?new Date(session.startedAt).toLocaleDateString():'Start unavailable'}</small></span><div role="cell" className="session-token-cell"><span>{number(r.inclusiveTokens)} total</span><small>{number(r.directTokens)} direct · {number(r.descendantTokens)} descendant</small><div className="session-inline-chart" role="img" aria-label={`${number(r.inclusiveTokens)} total tokens: ${number(r.directTokens)} direct and ${number(r.descendantTokens)} descendant`}><ResponsiveContainer width="100%" height={8}><BarChart layout="vertical" data={[{name:r.rootSessionId,direct:r.directTokens,descendant:r.descendantTokens}]} margin={{top:0,right:0,bottom:0,left:0}}><XAxis type="number" domain={[0,maxSessionTokens]} hide/><YAxis type="category" dataKey="name" hide/><Bar dataKey="direct" stackId="session" fill="#1e5a50" isAnimationActive={false}/><Bar dataKey="descendant" stackId="session" fill="#7da58b" isAnimationActive={false}/></BarChart></ResponsiveContainer></div></div><div role="cell" className="session-actions-cell"><a className="review-link" href={`/reviews/new?session=${encodeURIComponent(r.rootSessionId)}`}>Review effectiveness</a></div></div>})}</div></article>
      <article className="wide"><h2>Recorded capacity drawdown</h2>{drawdown?.coverage.fidelity==='unavailable'?<p>Unavailable — {drawdown.coverage.reason}.</p>:capacityChart.length?<><div className="chart-frame capacity-drawdown-chart" role="img" aria-label="Recorded capacity drawdown bar chart, with utilization percentage on the vertical axis"><ResponsiveContainer width="100%" height={280}><BarChart data={capacityChart} margin={{top:20,right:24,bottom:20,left:8}} barCategoryGap="24%"><CartesianGrid vertical={false} stroke="#e1dccf"/><XAxis dataKey="observedAt" type="number" scale="time" domain={['dataMin','dataMax']} minTickGap={48} tickFormatter={value=>new Date(value).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})} label={{value:'Recorded time',position:'insideBottom',offset:-12,fill:'#69736d',fontSize:11}} tick={{fontSize:10,fill:'#69736d'}}/><YAxis domain={[0,100]} unit="%" label={{value:'Utilization',angle:-90,position:'insideLeft',fill:'#69736d',fontSize:11}} tick={{fontSize:10,fill:'#69736d'}}/><ChartTooltip labelFormatter={value=>new Date(Number(value)).toLocaleString()} formatter={(value,name)=>[`${value}%`,name]}/><Legend verticalAlign="top" align="right"/>{capacityHistory.map((window,index)=><Bar key={window.dataKey} dataKey={window.dataKey} name={`${window.limitId} · ${window.windowMinutes}m`} fill={capacityColors[index%capacityColors.length]} maxBarSize={28} isAnimationActive={false}/>)}</BarChart></ResponsiveContainer></div><ul className="capacity-series">{capacityHistory.map(window=><li key={window.dataKey}><strong>{window.limitId} · {window.windowMinutes} minute window</strong><span>{window.points.length} recorded observation{window.points.length===1?'':'s'} across {window.resetBoundaries.size} reset period{window.resetBoundaries.size===1?'':'s'} · {Math.min(...window.points.map((point:any)=>point.usedPercent))}%–{Math.max(...window.points.map((point:any)=>point.usedPercent))}% used</span></li>)}</ul></>:<p>No recorded observations in the selected time range.</p>}<small>Each bar is one source-recorded utilization observation. Limit windows stay separate while reset periods share one legend entry; local token use is not claimed to cause plan utilization.</small></article></section>}
    </>}
    <details><summary>Status &amp; diagnostics</summary><dl className="diagnostics-grid"><dt>Effective home</dt><dd>{status.sourceHome?.path||'Unavailable'} ({status.sourceHome?.resolution||'unknown'})</dd><dt>Process</dt><dd>{status.process.inspectorVersion} · CLI {status.process.cliVersion} · {status.process.cliCompatibility}</dd><dt>Index</dt><dd>{status.index.state} · snapshot r{applied??status.appliedRevision} · latest r{status.index.appliedRevision}</dd><dt>Progress</dt><dd>{status.index.processedCount} processed · {status.index.remainingCount} remaining · {status.index.skippedCount} skipped</dd><dt>Sources</dt><dd>{status.index.supportedSourceCount} supported · {status.index.unsupportedSourceCount} unsupported · {status.index.failedCount} failed · {status.index.requiresRebuildCount} rebuild required</dd><dt>Completed-turn watermark</dt><dd>{status.index.completedWatermark||'Not available'}</dd><dt>Database</dt><dd>{number(status.index.databaseBytes)} bytes</dd><dt>Hook health</dt><dd>{status.hook.state}{status.hook.diagnostics.length?` · ${status.hook.diagnostics.map(x=>`${x.code} (${x.count})`).join(', ')}`:''}</dd></dl>{status.index.diagnosticGroups.length>0?<section className="diagnostic-groups" aria-labelledby="source-limits-heading"><h3 id="source-limits-heading">Sources requiring attention</h3>{status.index.diagnosticGroups.map((group,index)=><article key={`${group.state}-${group.reason}-${group.detectedVersion}-${index}`}><div><Badge variant={group.state==='failed'?'destructive':'secondary'}>{group.state.replaceAll('_',' ')}</Badge><strong>{group.count} source{group.count===1?'':'s'} · Codex {group.detectedVersion}</strong></div><code>{group.reason}</code><p>{group.remediation}</p></article>)}</section>:<p>No unsupported, failed, or rebuild-required source groups are present.</p>}<p>These diagnostics contain counts, structural reasons, and detected versions—not source paths or payloads.</p><Button size="sm" variant="outline" onClick={()=>void navigator.clipboard.writeText(diagnostics(status)).then(()=>setCopied(true))}>Copy payload-safe doctor diagnostics</Button>{copied&&<small>Copied</small>}<pre>{diagnostics(status)}</pre></details>
  </section></AppShell>
}
