/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import React from 'react'
import {establishSession,fetchFilterOptions,fetchStatus,queryMetrics,subscribe,type DashboardQuery,type FilterOptions,type MetricResult,type Status} from './api'
import {capacityCountdown} from './capacity'
import {ContextInspector} from './context-inspector'

const keys=['recorded_tokens','recorded_tokens_by_kind','recorded_tokens_over_time','token_composition','top_root_sessions_by_tokens','latest_capacity_observation','capacity_drawdown']
const fallbackKinds:FilterOptions['contributionKinds']=[{value:'user_root_direct',label:'User root'},{value:'descendant',label:'Descendants'},{value:'inspector_review',label:'Inspector Review'},{value:'other_orphan',label:'Other / orphan'}]
type Item={key:string;value:any;fidelity:string;coverage:{fidelity:string;observed:number;eligible:number;reason?:string};indexedCoverage:{indexedStart:string|null;indexedEnd:string|null;completedWatermark:string|null};exclusionReasons:Record<string,number>}
const item=(data:MetricResult|null,key:string)=>data?.results?.find((x:any)=>x.key===key) as unknown as Item|undefined
const number=(value:number|null|undefined)=>value==null?'Unavailable':new Intl.NumberFormat().format(value)
const bucketTotal=(values:Record<string,number>)=>Object.values(values).reduce((sum,value)=>sum+value,0)
const camel=(value:string)=>value.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase())
function diagnostics(status:Status){return JSON.stringify({summary:'Payload-safe Inspector runtime checks.',index:{state:status.index.state,sources:status.index.sourceCount,supported:status.index.supportedSourceCount,unsupported:status.index.unsupportedSourceCount,failed:status.index.failedCount,schemaVersion:status.index.schemaVersion},hook:{state:status.hook.state,diagnostics:status.hook.diagnostics}},null,2)}

export function App(){
  const [status,setStatus]=React.useState<Status|null>(null),[data,setData]=React.useState<MetricResult|null>(null),[error,setError]=React.useState('')
  const [options,setOptions]=React.useState<FilterOptions>({projects:[],models:[],reasoningEfforts:[],contributionKinds:fallbackKinds})
  const [range,setRange]=React.useState('30'),[project,setProject]=React.useState(''),[model,setModel]=React.useState(''),[reasoning,setReasoning]=React.useState(''),[kind,setKind]=React.useState('')
  const [applied,setApplied]=React.useState<number|null>(null),[available,setAvailable]=React.useState<number|null>(null),[indexing,setIndexing]=React.useState(false),[now,setNow]=React.useState(Date.now())
  const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'
  const buildQuery=React.useCallback((revision?:number)=>{const q:DashboardQuery={metricKeys:keys,timezone,grain:range==='all'?'month':Number(range)<=2?'hour':'day',projectIds:project?[project]:undefined,models:model?[model]:undefined,reasoningEfforts:reasoning?[reasoning]:undefined,contributionKinds:kind?[kind]:undefined,requestedRevision:revision};if(range!=='all'){const end=new Date(),start=new Date(end.getTime()-Number(range)*86400000);q.start=start.toISOString();q.end=end.toISOString()}return q},[range,project,model,reasoning,kind,timezone])
  const loadMetrics=React.useCallback(async(revision?:number)=>{const result=await queryMetrics(buildQuery(revision));setData(result);setApplied(result.appliedRevision);return result},[buildQuery])
  const refreshStatus=React.useCallback(async()=>{const fresh=await fetchStatus();setStatus(fresh);setIndexing(fresh.index.state==='building'||fresh.index.state==='catching_up');return fresh},[])
  React.useEffect(()=>{let off=()=>{},active=true;establishSession().then(async initial=>{const catalog=await fetchFilterOptions(initial.appliedRevision);if(!active)return;setStatus(initial);setOptions(catalog);setApplied(initial.appliedRevision);setIndexing(initial.index.state==='building'||initial.index.state==='catching_up');if(initial.index.state!=='empty'&&initial.process.cliCompatibility==='supported'&&initial.process.pluginVersion)await loadMetrics(initial.appliedRevision);off=subscribe(ev=>{if(ev.event==='revision.available'){if(ev.data.fullRefreshRequired){location.reload();return}setAvailable(Number(ev.data.revision));void refreshStatus()}else if(ev.event==='status.changed'||ev.event==='sync.progress'){setIndexing(ev.data.state==='scanning'||ev.data.state==='catching_up'||Number(ev.data.queued)>0);void refreshStatus()}})}).catch((e:Error)=>setError(e.message));const heartbeat=setInterval(()=>void fetch('/v1/heartbeat',{method:'POST'}),15000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{active=false;clearInterval(heartbeat);clearInterval(clock);off()}},[])
  React.useEffect(()=>{if(applied!=null&&status?.index.state!=='empty'&&status?.process.cliCompatibility==='supported'&&status.process.pluginVersion)void loadMetrics(applied).catch(e=>setError(e.message))},[range,project,model,reasoning,kind])
  const applyAvailable=async()=>{if(available==null)return;const [,catalog]=await Promise.all([loadMetrics(available),fetchFilterOptions(available)]);setOptions(catalog);await refreshStatus();setAvailable(null)}
  if(error)return <main><h1>Codex Inspector</h1><section className="error"><h2>Unable to open Inspector</h2><p>{error}</p><code>codex-inspector doctor</code></section></main>
  if(!status)return <main><h1>Codex Inspector</h1><p>Establishing a secure local session…</p></main>
  const setup=!status.process.pluginVersion||status.process.cliCompatibility==='unknown',incompatible=status.process.cliCompatibility==='unsupported',empty=status.index.state==='empty'&&!data,total=item(data,'recorded_tokens'),byKind=item(data,'recorded_tokens_by_kind'),composition=item(data,'token_composition'),overTime=item(data,'recorded_tokens_over_time'),roots=item(data,'top_root_sessions_by_tokens'),latest=item(data,'latest_capacity_observation'),drawdown=item(data,'capacity_drawdown')
  const partial=!!data&&(data.coverage.fidelity!=='exact'||data.coverage.observed<data.coverage.eligible||status.index.unsupportedSourceCount>0||status.index.failedCount>0||indexing)
  const capacity=latest?.value,capacityStale=capacity?now>=new Date(capacity.resetsAt).getTime():false,kinds=options.contributionKinds.length?options.contributionKinds:fallbackKinds
  if(location.pathname.startsWith('/context')&&!setup&&!incompatible)return <ContextInspector revision={applied??status.appliedRevision} available={available} onApply={applyAvailable}/>
  return <main><header><div><span className="eyebrow">LOCAL OBSERVABILITY</span><h1>Token &amp; Capacity</h1></div><span className="pill">{indexing?'Indexing':status.index.state}</span></header>
    {available!=null&&available!==applied&&<button className="new-data" onClick={()=>void applyAvailable()}>New data available — apply</button>}
    {setup?<section className="error"><h2>Finish Inspector setup</h2><p>Install and enable the matching plugin, then review its seven hooks.</p></section>:incompatible?<section className="error"><h2>Inspector versions are incompatible</h2><p>The installed host, plugin, or source format is outside the supported demo contract.</p></section>:empty?<section className="empty"><h2>Ready for your first sync</h2><p>No recorded usage yet. Sync supported Codex rollouts to populate this view.</p><button onClick={()=>{setIndexing(true);void fetch('/v1/sync',{method:'POST',headers:{'content-type':'application/json'},body:'{"mode":"background"}'})}}>Start sync</button></section>:<>
      <section className="filters" aria-label="Dashboard filters"><label>Time<select value={range} onChange={e=>setRange(e.target.value)}><option value="2">48 hours</option><option value="7">7 days</option><option value="30">30 days</option><option value="all">All indexed</option></select></label><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">All projects</option>{options.projects.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)}><option value="">All models</option>{options.models.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Reasoning<select value={reasoning} onChange={e=>setReasoning(e.target.value)}><option value="">All levels</option>{options.reasoningEfforts.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Contribution<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">All kinds</option>{kinds.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></section>
      {partial&&<section className="warning" role="status"><strong>Partial recorded coverage</strong><p>These totals cover {data?.coverage.observed} of {data?.coverage.eligible} eligible completed turns. {status.index.unsupportedSourceCount} sources are unsupported and {status.index.failedCount} failed. They are not presented as complete history.</p></section>}
      <section className="grid"><article><h2>Recorded capacity</h2>{capacity?<><strong className="hero">{capacity.usedPercent}% used</strong><p>Recorded {new Date(capacity.observedAt).toLocaleString()} · {capacityCountdown(capacity.resetsAt,now)}</p>{(capacityStale||latest?.coverage.fidelity!=='exact')&&<span className="stale">{capacityStale?'Stale recorded observation':'Partial capacity coverage'}</span>}</>:<p>Unavailable — {latest?.coverage.reason||'no supported capacity observation was recorded'}.</p>}<small>Account-wide point-in-time source observation. Not inferred from local tokens or changed by project/model filters.</small></article>
      <article><h2>Total recorded tokens</h2>{total?.coverage.fidelity==='unavailable'?<><strong className="hero">Unavailable</strong><p>{total.coverage.reason}</p></>:<strong className="hero">{number(total?.value)}</strong>}<div className="legend">{byKind&&kinds.map(x=><span key={x.value}>{x.label}: {number(byKind.value[camel(x.value)])}</span>)}</div></article>
      <article className="wide"><h2>Recorded usage over time</h2><div className="bars">{(overTime?.value||[]).map((b:any)=><div className="bar-row" key={b.bucketStart}><time>{new Date(b.bucketStart).toLocaleDateString()}</time><div className="bar" title={`${bucketTotal(b.byKind)} tokens`} style={{width:`${Math.max(2,Math.min(100,bucketTotal(b.byKind)/Math.max(1,total?.value||1)*100))}%`}}/></div>)}</div></article>
      <article><h2>Token composition</h2>{composition?.coverage.fidelity==='unavailable'?<p>Unavailable — {composition.coverage.reason}.</p>:composition&&<><dl className="compact"><dt>Uncached input</dt><dd>{number(composition.value.uncachedInput)}</dd><dt>Cached input</dt><dd>{number(composition.value.cachedInput)}</dd><dt>Visible output</dt><dd>{number(composition.value.visibleOutput)}</dd><dt>Reasoning output</dt><dd>{number(composition.value.reasoningOutput)}</dd><dt>Residual</dt><dd>{number(composition.value.residual)}</dd></dl>{composition.coverage.fidelity!=='exact'&&<p className="stale">Partial: {composition.coverage.observed} of {composition.coverage.eligible} turns</p>}</>}<small>Components are mutually exclusive; cached input and reasoning output are not counted twice.</small></article>
      <article><h2>Top root sessions</h2><ol className="sessions">{(roots?.value||[]).slice(0,10).map((r:any)=><li key={r.rootSessionId}><a href={`/context/${encodeURIComponent(r.rootSessionId)}`}>{number(r.inclusiveTokens)} tokens</a><small>{number(r.directTokens)} direct · {number(r.descendantTokens)} descendant</small></li>)}</ol></article>
      <article className="wide"><h2>Recorded capacity drawdown</h2>{drawdown?.coverage.fidelity==='unavailable'?<p>Unavailable — {drawdown.coverage.reason}.</p>:(drawdown?.value||[]).length?<div className="capacity-series">{(drawdown?.value||[]).map((s:any)=><div key={`${s.limitId}-${s.resetBoundary}`}><strong>{s.limitId} · {s.windowMinutes} minute window</strong><p>{s.points.map((p:any)=>`${p.usedPercent}% at ${new Date(p.observedAt).toLocaleTimeString()}`).join(' → ')}</p></div>)}</div>:<p>No recorded observations in the selected time range.</p>}<small>Gaps are not interpolated and local token use is not claimed to cause plan utilization.</small></article></section>
    </>}
    <details><summary>Status &amp; diagnostics</summary><p>{status.index.processedCount} processed · {status.index.skippedCount} skipped · {status.index.failedCount} failed · revision {applied}</p><pre>{diagnostics(status)}</pre></details><aside>Sensitive-data notice: evidence views may display exact local payloads.</aside>
  </main>
}
