/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import React from 'react'
import {establishSession,fetchFilterOptions,fetchSessions,fetchStatus,queryMetrics,subscribe,type DashboardQuery,type FilterOptions,type MetricResult,type SessionPage,type Status} from './api'
import {capacityCountdown} from './capacity'
import {ContextInspector} from './context-inspector'
import {Reviews} from './reviews'
import {AppShell} from './app-shell'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const keys=['recorded_tokens','recorded_tokens_by_kind','recorded_tokens_over_time','token_composition','top_root_sessions_by_tokens','latest_capacity_observation','capacity_drawdown']
const fallbackKinds:FilterOptions['contributionKinds']=[{value:'user_root_direct',label:'User root'},{value:'descendant',label:'Descendants'},{value:'inspector_review',label:'Inspector Review'},{value:'other_orphan',label:'Other / orphan'}]
type Item={key:string;value:any;fidelity:string;coverage:{fidelity:string;observed:number;eligible:number;reason?:string};indexedCoverage:{indexedStart:string|null;indexedEnd:string|null;completedWatermark:string|null};exclusionReasons:Record<string,number>}
const item=(data:MetricResult|null,key:string)=>data?.results?.find((x:any)=>x.key===key) as unknown as Item|undefined
const number=(value:number|null|undefined)=>value==null?'Unavailable':new Intl.NumberFormat().format(value)
const camel=(value:string)=>value.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase())
function diagnostics(status:Status){return JSON.stringify({summary:'Payload-safe Inspector runtime checks.',index:{state:status.index.state,sources:status.index.sourceCount,supported:status.index.supportedSourceCount,unsupported:status.index.unsupportedSourceCount,failed:status.index.failedCount,schemaVersion:status.index.schemaVersion},hook:{state:status.hook.state,diagnostics:status.hook.diagnostics}},null,2)}

export function App(){
  const [status,setStatus]=React.useState<Status|null>(null),[data,setData]=React.useState<MetricResult|null>(null),[sessions,setSessions]=React.useState<SessionPage['items']>([]),[error,setError]=React.useState('')
  const [options,setOptions]=React.useState<FilterOptions>({projects:[],models:[],reasoningEfforts:[],contributionKinds:fallbackKinds})
  const [range,setRange]=React.useState('30'),[project,setProject]=React.useState(''),[model,setModel]=React.useState(''),[reasoning,setReasoning]=React.useState(''),[kind,setKind]=React.useState('')
  const [applied,setApplied]=React.useState<number|null>(null),[available,setAvailable]=React.useState<number|null>(null),[indexing,setIndexing]=React.useState(false),[now,setNow]=React.useState(Date.now()),[coverageOpen,setCoverageOpen]=React.useState(false),[copied,setCopied]=React.useState(false)
  const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'
  const buildQuery=React.useCallback((revision?:number)=>{const q:DashboardQuery={metricKeys:keys,timezone,grain:range==='all'?'month':Number(range)<=2?'hour':'day',projectIds:project?[project]:undefined,models:model?[model]:undefined,reasoningEfforts:reasoning?[reasoning]:undefined,contributionKinds:kind?[kind]:undefined,requestedRevision:revision};if(range!=='all'){const end=new Date(),start=new Date(end.getTime()-Number(range)*86400000);q.start=start.toISOString();q.end=end.toISOString()}return q},[range,project,model,reasoning,kind,timezone])
  const loadMetrics=React.useCallback(async(revision?:number)=>{const result=await queryMetrics(buildQuery(revision));setData(result);setApplied(result.appliedRevision);return result},[buildQuery])
  const refreshStatus=React.useCallback(async()=>{const fresh=await fetchStatus();setStatus(fresh);setIndexing(fresh.index.state==='building'||fresh.index.state==='catching_up');return fresh},[])
  React.useEffect(()=>{let off=()=>{},active=true;establishSession().then(async initial=>{const catalog=await fetchFilterOptions(initial.appliedRevision);if(!active)return;setStatus(initial);setOptions(catalog);setApplied(initial.appliedRevision);setIndexing(initial.index.state==='building'||initial.index.state==='catching_up');if(initial.index.state!=='empty'&&initial.process.cliCompatibility==='supported'&&initial.process.pluginVersion)await loadMetrics(initial.appliedRevision);off=subscribe(ev=>{if(ev.event==='revision.available'){if(ev.data.fullRefreshRequired){location.reload();return}setAvailable(Number(ev.data.revision));void refreshStatus()}else if(ev.event==='status.changed'||ev.event==='sync.progress'){setIndexing(ev.data.state==='scanning'||ev.data.state==='catching_up'||Number(ev.data.queued)>0);void refreshStatus()}})}).catch((e:Error)=>setError(e.message));const heartbeat=setInterval(()=>void fetch('/v1/heartbeat',{method:'POST'}),15000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{active=false;clearInterval(heartbeat);clearInterval(clock);off()}},[])
  React.useEffect(()=>{if(applied!=null&&status?.index.state!=='empty'&&status?.process.cliCompatibility==='supported'&&status.process.pluginVersion)void loadMetrics(applied).catch(e=>setError(e.message))},[range,project,model,reasoning,kind])
  React.useEffect(()=>{if(applied!=null)void fetchSessions('',applied).then(page=>setSessions(Array.isArray(page.items)?page.items:[])).catch(()=>setSessions([]))},[applied])
  const applyAvailable=async()=>{if(available==null)return;const [,catalog]=await Promise.all([loadMetrics(available),fetchFilterOptions(available)]);setOptions(catalog);await refreshStatus();setAvailable(null)}
  if(error)return <main><h1>Codex Inspector</h1><section className="error"><h2>Unable to open Inspector</h2><p>{error}</p><code>codex-inspector doctor</code></section></main>
  if(!status)return <main><h1>Codex Inspector</h1><p>Establishing a secure local session…</p></main>
  const setup=!status.process.pluginVersion||status.process.cliCompatibility==='unknown',incompatible=status.process.cliCompatibility==='unsupported',empty=status.index.state==='empty'&&!data,total=item(data,'recorded_tokens'),byKind=item(data,'recorded_tokens_by_kind'),composition=item(data,'token_composition'),overTime=item(data,'recorded_tokens_over_time'),roots=item(data,'top_root_sessions_by_tokens'),latest=item(data,'latest_capacity_observation'),drawdown=item(data,'capacity_drawdown')
  const partial=!!data&&(data.coverage.fidelity!=='exact'||data.coverage.observed<data.coverage.eligible||status.index.unsupportedSourceCount>0||status.index.failedCount>0||indexing)
  const capacity=latest?.value,capacityStale=capacity?now>=new Date(capacity.resetsAt).getTime():false,kinds=options.contributionKinds.length?options.contributionKinds:fallbackKinds
  if(location.pathname.startsWith('/context')&&!setup&&!incompatible)return <AppShell status={status}><ContextInspector revision={applied??status.appliedRevision} available={available} onApply={applyAvailable}/></AppShell>
  if(location.pathname.startsWith('/reviews')&&!setup&&!incompatible)return <AppShell status={status}><Reviews revision={applied??status.appliedRevision} projects={options.projects}/></AppShell>
  const usageChart=(overTime?.value||[]).map((bucket:any)=>({bucket:new Date(bucket.bucketStart).toLocaleDateString(undefined,{month:'short',day:'numeric'}),user_root_direct:bucket.byKind.userRootDirect||0,descendant:bucket.byKind.descendant||0,inspector_review:bucket.byKind.inspectorReview||0,other_orphan:bucket.byKind.otherOrphan||0}))
  const capacityChart=(drawdown?.value||[]).flatMap((series:any)=>series.points.map((point:any)=>({observedAt:new Date(point.observedAt).toLocaleString(),usedPercent:point.usedPercent,window:`${series.limitId} · ${series.windowMinutes}m`,reset:series.resetBoundary})))
  const sessionByID=new Map(sessions.map(session=>[session.sessionId,session]))
  return <AppShell status={status}><section className="dashboard-page"><header><div><span className="eyebrow">LOCAL OBSERVABILITY</span><h1>Token &amp; Capacity</h1><p className="page-purpose">A source-backed read of completed local Codex work and recorded plan capacity.</p></div><div className="dashboard-status"><Badge variant="outline">Snapshot r{applied??status.appliedRevision}</Badge><Badge variant={indexing?'secondary':'outline'}>{indexing?'Indexing local history':status.index.state}</Badge></div></header>
    {available!=null&&available!==applied&&<Button className="new-data" onClick={()=>void applyAvailable()}>New data available — apply</Button>}
    {setup?<section className="error"><h2>Finish Inspector setup</h2><p>Install and enable the matching plugin, then review its seven hooks.</p></section>:incompatible?<section className="error"><h2>Inspector versions are incompatible</h2><p>The installed host, plugin, or source format is outside the supported demo contract.</p></section>:empty?<section className="empty"><h2>Ready for your first sync</h2><p>No recorded usage yet. Sync supported Codex rollouts to populate this view.</p><Button onClick={()=>{setIndexing(true);void fetch('/v1/sync',{method:'POST',headers:{'content-type':'application/json'},body:'{"mode":"background"}'})}}>Start sync</Button></section>:<>
      <section className="filters" aria-label="Dashboard filters"><label>Time<select value={range} onChange={e=>setRange(e.target.value)}><option value="2">48 hours</option><option value="7">7 days</option><option value="30">30 days</option><option value="all">All indexed</option></select></label><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">All projects</option>{options.projects.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)}><option value="">All models</option>{options.models.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Reasoning<select value={reasoning} onChange={e=>setReasoning(e.target.value)}><option value="">All levels</option>{options.reasoningEfforts.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Contribution<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">All kinds</option>{kinds.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></section>
      {partial&&<Alert className="coverage-alert" role="status"><AlertTitle>Partial recorded coverage</AlertTitle><AlertDescription>These totals cover {data?.coverage.observed} of {data?.coverage.eligible} eligible completed turns. {status.index.unsupportedSourceCount} sources are unsupported and {status.index.failedCount} failed. <Sheet open={coverageOpen} onOpenChange={setCoverageOpen}><SheetTrigger asChild><Button variant="link" size="sm">Coverage details</Button></SheetTrigger><SheetContent><SheetHeader><SheetTitle>Coverage details</SheetTitle><SheetDescription>Inspector never fills gaps with estimates.</SheetDescription></SheetHeader><div className="coverage-details"><dl><dt>Observed eligible turns</dt><dd>{data?.coverage.observed} / {data?.coverage.eligible}</dd><dt>Supported sources</dt><dd>{status.index.supportedSourceCount}</dd><dt>Unsupported sources</dt><dd>{status.index.unsupportedSourceCount}</dd><dt>Failed sources</dt><dd>{status.index.failedCount}</dd><dt>Incomplete active tails</dt><dd>{status.index.pendingTailCount}</dd><dt>Rebuild required</dt><dd>{status.index.requiresRebuildCount}</dd></dl><p>Use Status &amp; diagnostics for payload-safe rejection groups and remediation.</p></div></SheetContent></Sheet></AlertDescription></Alert>}
      <section className="grid"><article><h2>Recorded capacity</h2>{capacity?<><strong className="hero">{capacity.usedPercent}% used</strong><p>{capacity.remainingPercent==null?`${100-capacity.usedPercent}% remaining (derived)`: `${capacity.remainingPercent}% remaining (recorded)`}</p><p>Recorded {new Date(capacity.observedAt).toLocaleString()} · resets locally {new Date(capacity.resetsAt).toLocaleString()} · {capacityCountdown(capacity.resetsAt,now)}</p>{(capacityStale||latest?.coverage.fidelity!=='exact')&&<span className="stale">{capacityStale?'Stale recorded observation':'Partial capacity coverage'}</span>}</>:<p>Unavailable — {latest?.coverage.reason||'no supported capacity observation was recorded'}.</p>}<small>Account-wide point-in-time source observation. Not inferred from local tokens or changed by project/model filters.</small></article>
      <article><h2>Total recorded tokens</h2>{total?.coverage.fidelity==='unavailable'?<><strong className="hero">Unavailable</strong><p>{total.coverage.reason}</p></>:<strong className="hero">{number(total?.value)}</strong>}<div className="legend">{byKind&&kinds.map(x=><span key={x.value}>{x.label}: {number(byKind.value[camel(x.value)])}</span>)}</div></article>
      <article className="wide"><h2>Recorded usage over time</h2><div className="chart-frame" aria-label="Stacked token contribution chart"><ResponsiveContainer width="100%" height={260}><BarChart data={usageChart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Legend/><Bar dataKey="user_root_direct" name="User root direct" stackId="usage" fill="#1e5a50"/><Bar dataKey="descendant" name="Descendant" stackId="usage" fill="#7da58b"/><Bar dataKey="inspector_review" name="Inspector Review" stackId="usage" fill="#d6ad58"/><Bar dataKey="other_orphan" name="Other / orphan" stackId="usage" fill="#a97770"/></BarChart></ResponsiveContainer></div><p className="chart-summary">{usageChart.length ? `${usageChart.length} recorded time buckets shown with an accessible legend and tooltip.` : 'No recorded usage falls within this range.'}</p></article>
      <article><h2>Token composition</h2>{composition?.coverage.fidelity==='unavailable'?<p>Unavailable — {composition.coverage.reason}.</p>:composition&&<><dl className="compact"><dt>Uncached input</dt><dd>{number(composition.value.uncachedInput)}</dd><dt>Cached input</dt><dd>{number(composition.value.cachedInput)}</dd><dt>Visible output</dt><dd>{number(composition.value.visibleOutput)}</dd><dt>Reasoning output</dt><dd>{number(composition.value.reasoningOutput)}</dd><dt>Residual</dt><dd>{number(composition.value.residual)}</dd></dl>{composition.coverage.fidelity!=='exact'&&<p className="stale">Partial: {composition.coverage.observed} of {composition.coverage.eligible} turns</p>}</>}<small>Components are mutually exclusive; cached input and reasoning output are not counted twice.</small></article>
      <article className="wide"><h2>Top root sessions</h2><div className="session-table" role="table" aria-label="Top root sessions"><div role="row" className="session-table-head"><span role="columnheader">Session</span><span role="columnheader">Project / start</span><span role="columnheader">Tokens</span><span role="columnheader">Actions</span></div>{(roots?.value||[]).slice(0,10).map((r:any)=>{const session=sessionByID.get(r.rootSessionId);const title=session?.title?.trim()||`Recorded session ${r.rootSessionId.slice(0,8)}`;return <div role="row" key={r.rootSessionId}><a href={`/context/${encodeURIComponent(r.rootSessionId)}`}><strong>{title}</strong><small>{session?.completedTurns??'—'} completed turns</small></a><span role="cell">{session?.project||'Project unavailable'}<small>{session?.startedAt?new Date(session.startedAt).toLocaleDateString():'Start unavailable'}</small></span><span role="cell">{number(r.inclusiveTokens)} total<small>{number(r.directTokens)} direct · {number(r.descendantTokens)} descendant</small></span><a className="review-link" href={`/reviews/new?session=${encodeURIComponent(r.rootSessionId)}`}>Review effectiveness</a></div>})}</div></article>
      <article className="wide"><h2>Recorded capacity drawdown</h2>{drawdown?.coverage.fidelity==='unavailable'?<p>Unavailable — {drawdown.coverage.reason}.</p>:capacityChart.length?<><div className="chart-frame" aria-label="Recorded capacity drawdown chart"><ResponsiveContainer width="100%" height={250}><LineChart data={capacityChart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="observedAt" hide/><YAxis domain={[0,100]} unit="%"/><Tooltip/><Legend/><Line type="monotone" dataKey="usedPercent" name="Used capacity" stroke="#a64032" strokeWidth={2} dot/></LineChart></ResponsiveContainer></div><ul className="capacity-series">{(drawdown?.value||[]).map((s:any)=><li key={`${s.limitId}-${s.resetBoundary}`}><strong>{s.limitId} · {s.windowMinutes} minute window</strong><span>{s.points.length} recorded observation{s.points.length===1?'':'s'} · reset {new Date(s.resetBoundary).toLocaleString()}</span></li>)}</ul></>:<p>No recorded observations in the selected time range.</p>}<small>Gaps are not interpolated and local token use is not claimed to cause plan utilization.</small></article></section>
    </>}
    <details><summary>Status &amp; diagnostics</summary><dl className="diagnostics-grid"><dt>Effective home</dt><dd>{status.sourceHome?.path||'Unavailable'} ({status.sourceHome?.resolution||'unknown'})</dd><dt>Process</dt><dd>{status.process.inspectorVersion} · CLI {status.process.cliVersion} · {status.process.cliCompatibility}</dd><dt>Index</dt><dd>{status.index.state} · snapshot r{applied??status.appliedRevision} · latest r{status.index.appliedRevision}</dd><dt>Progress</dt><dd>{status.index.processedCount} processed · {status.index.remainingCount} remaining · {status.index.skippedCount} skipped</dd><dt>Sources</dt><dd>{status.index.supportedSourceCount} supported · {status.index.unsupportedSourceCount} unsupported · {status.index.failedCount} failed · {status.index.requiresRebuildCount} rebuild required</dd><dt>Completed-turn watermark</dt><dd>{status.index.completedWatermark||'Not available'}</dd><dt>Database</dt><dd>{number(status.index.databaseBytes)} bytes</dd><dt>Hook health</dt><dd>{status.hook.state}{status.hook.diagnostics.length?` · ${status.hook.diagnostics.map(x=>`${x.code} (${x.count})`).join(', ')}`:''}</dd></dl><p>Diagnostics exclude source payloads. Exact source text is available only beside the selected Context Inspector evidence. {status.index.failedCount||status.index.requiresRebuildCount?'Review unsupported/failed sources and run a background sync after resolving local source issues.':'No remediation is currently required.'}</p><Button size="sm" variant="outline" onClick={()=>void navigator.clipboard.writeText(diagnostics(status)).then(()=>setCopied(true))}>Copy payload-safe doctor diagnostics</Button>{copied&&<small>Copied</small>}<pre>{diagnostics(status)}</pre></details>
  </section></AppShell>
}
