/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react'
import {ArrowRight,LoaderCircle} from 'lucide-react'
import {fetchEvidence,fetchLedger,fetchRecordedContext,fetchSessionMap,fetchSessionMetadata,fetchSessions,type EvidenceChunk,type LedgerPage,type RecordedContext,type SessionMap,type SessionPage} from './api'
import {navigate} from './navigation'

type Props={revision:number;available:number|null;onApply:()=>Promise<void>}
type Route={sessionId?:string;turnId?:string;eventId?:string;evidenceId?:string}

function route():Route{
  const parts=location.pathname.split('/').filter(Boolean).map(value=>{try{return decodeURIComponent(value)}catch{return ''}})
  if(parts[0]!=='context')return {}
  const eventIndex=parts.indexOf('event'),turnIndex=parts.indexOf('turn')
  return {sessionId:parts[1],turnId:turnIndex>=0?parts[turnIndex+1]:undefined,eventId:eventIndex>=0?parts[eventIndex+1]:undefined,evidenceId:new URLSearchParams(location.search).get('evidence')||undefined}
}
function inspectorPath(path:string,updates:Record<string,string|undefined>={}){const current=new URLSearchParams(location.search),next=new URLSearchParams();for(const key of ['q','return']){const value=current.get(key);if(value)next.set(key,value)}for(const [key,value] of Object.entries(updates)){if(value)next.set(key,value);else next.delete(key)}return `${path}${next.size?`?${next}`:''}`}
const tokens=(value:number|null|undefined)=>value==null?'Unavailable':new Intl.NumberFormat().format(value)
const kindLabel=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())
const usableTitle=(value:string|undefined)=>{const title=value?.trim()||'';return title&&!/^<(environment_context|system|developer|image)\b/i.test(title)&&!/^\{["']?(cwd|shell|current_date)["']?\s*:/i.test(title)&&!/^the following is the codex agent history/i.test(title)?title:''}
const projectName=(value:string|undefined)=>{if(!value)return '';try{const url=new URL(value);return url.pathname.split('/').filter(Boolean).at(-1)||url.hostname}catch{return value.replace(/[\\/]$/,'').split(/[\\/]/).filter(Boolean).at(-1)||value}}
const sessionTitle=(item:SessionPage['items'][number])=>usableTitle(item.title)||[projectName(item.project),item.startedAt&&new Date(item.startedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})].filter(Boolean).join(' · ')||`Session ${item.sessionId.slice(-8)}`
const matchLabel=(value:string)=>{const [scope,field]=value.split(':').map(part=>part.trim());if(!field)return value==='root session'?'Recent root session':kindLabel(value);return `${scope==='descendant'?'Spawned agent':'Root session'} matched ${field}`}
const sessionDuration=(item:SessionPage['items'][number])=>{if(!item.startedAt||!item.latestCompleted)return '';const elapsed=new Date(item.latestCompleted).getTime()-new Date(item.startedAt).getTime();if(!Number.isFinite(elapsed)||elapsed<0)return '';const minutes=Math.max(1,Math.round(elapsed/60000));return minutes<60?`${minutes} min`:`${Math.floor(minutes/60)} hr ${minutes%60?`${minutes%60} min`:''}`.trim()}
function Highlight({text,query}:{text:string;query:string}){const needles=[...new Set(query.trim().split(/\s+/).filter(Boolean).map(value=>value.toLowerCase()))];if(!needles.length)return <>{text}</>;const expression=needles.sort((a,b)=>b.length-a.length).map(value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),bits=text.split(new RegExp(`(${expression})`,'ig'));return <>{bits.map((part,index)=>needles.includes(part.toLowerCase())?<mark key={index}>{part}</mark>:<React.Fragment key={index}>{part}</React.Fragment>)}</>}
function EvidenceView({kind,observedAt,raw}:{kind:string;observedAt:string;raw:string}){let record:any;try{record=JSON.parse(raw)}catch{/* Exact record remains available below. */}const payload=record?.payload&&typeof record.payload==='object'?record.payload:{},type=typeof payload.type==='string'?payload.type:kind,label=kindLabel(type);const content=Array.isArray(payload.content)?payload.content.map((block:any)=>typeof block?.text==='string'?block.text:'').filter(Boolean).join('\n'):typeof payload.message==='string'?payload.message:typeof payload.last_agent_message==='string'?payload.last_agent_message:'';const toolName=typeof payload.name==='string'?payload.name:'';const toolInput=typeof payload.input==='string'?payload.input:typeof payload.arguments==='string'?payload.arguments:'';const toolOutput=typeof payload.output==='string'?payload.output:Array.isArray(payload.output)?payload.output.map((block:any)=>typeof block?.text==='string'?block.text:'').filter(Boolean).join('\n'):'';const description=type==='message'?`Recorded ${payload.role||'unknown-role'} message.`:type.includes('tool')||type.includes('function_call')?'Recorded tool activity.':type.includes('reasoning')?'Recorded reasoning summary; Inspector does not reconstruct omitted reasoning.':type.includes('token')||type.includes('rate')?'Recorded token or rate-limit observation.':type.includes('spawn')||type.includes('return')?'Recorded lineage event.':type.includes('compact')?'Recorded compaction event; no before/after reconstruction is claimed.':'Recorded lifecycle evidence.';return <div className="formatted-evidence"><div><span className="section-label">{label}</span><time>{new Date(observedAt).toLocaleString()}</time></div><h3>{label}</h3><p>{description}</p><dl>{payload.role&&<><dt>Role</dt><dd>{payload.role}</dd></>}{toolName&&<><dt>Tool</dt><dd>{toolName}</dd></>}{payload.call_id&&<><dt>Call ID</dt><dd>{payload.call_id}</dd></>}{payload.status&&<><dt>Status</dt><dd>{payload.status}</dd></>}</dl>{content&&<p className="formatted-content">{content}</p>}{toolInput&&<><h4>Recorded input</h4><pre>{toolInput}</pre></>}{toolOutput&&<><h4>Recorded result</h4><pre>{toolOutput}</pre></>}</div>}

export function ContextInspector({revision,available,onApply}:Props){
  const [routeState,setRoute]=React.useState(route())
  const returnTo=new URLSearchParams(location.search).get('return')
  React.useEffect(()=>{const update=()=>setRoute(route());addEventListener('popstate',update);return()=>removeEventListener('popstate',update)},[])
  return <section className="inspector-shell"><header><h1>Context Inspector</h1><nav>{returnTo&&returnTo.startsWith('/reviews/')&&<a className="quiet-link" href={returnTo}>Return to Review</a>}</nav></header>
    {available!=null&&available!==revision&&<button className="new-data" onClick={()=>void onApply()}>New data available — preserve this view &amp; apply</button>}
    {routeState.sessionId?<SessionView key={`${routeState.sessionId}:${revision}`} route={routeState} revision={revision}/>:<Discovery revision={revision}/>} 
  </section>
}

function Discovery({revision}:{revision:number}){
  const params=new URLSearchParams(location.search),notice=params.get('notice')
  const [query,setQuery]=React.useState(params.get('q')||''),[appliedQuery,setAppliedQuery]=React.useState(''),[result,setResult]=React.useState<SessionPage|null>(null),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true)
  const requestSequence=React.useRef(0),searchTimer=React.useRef<number|undefined>(undefined),searchController=React.useRef<AbortController|undefined>(undefined),initialQuery=React.useRef(query)
  const updateLocation=React.useCallback((value:string)=>{const next=new URLSearchParams(location.search);if(value.trim())next.set('q',value.trim());else next.delete('q');history.replaceState(null,'',`${location.pathname}${next.size?`?${next}`:''}`)},[])
  const search=React.useCallback(async(value:string)=>{const normalized=value.trim(),request=++requestSequence.current;searchController.current?.abort();const controller=new AbortController();searchController.current=controller;setLoading(true);setError('');try{const next=await fetchSessions(normalized,revision,undefined,controller.signal);if(request===requestSequence.current){setResult(next);setAppliedQuery(normalized)}}catch(e){if(request===requestSequence.current&&(e as Error).name!=='AbortError'){setError((e as Error).message);setAppliedQuery(normalized)}}finally{if(request===requestSequence.current)setLoading(false)}},[revision])
  const loadMore=async()=>{if(!result?.nextCursor)return;const next=await fetchSessions(appliedQuery,revision,result.nextCursor);setResult({...next,items:[...result.items,...next.items]})}
  React.useEffect(()=>{searchTimer.current=window.setTimeout(()=>{updateLocation(query);void search(query)},query===initialQuery.current?0:150);return()=>{window.clearTimeout(searchTimer.current);searchController.current?.abort()}},[query,search,updateLocation])
  const pending=loading||query.trim()!==appliedQuery
  return <section className="discovery">
    {notice==='current-session-unavailable'&&<div className="warning" role="status"><strong>Unable to locate the current session ID</strong><p>Inspector did not guess from the working directory or timestamps. Search the indexed session history instead.</p></div>}
    <form className="search-box" role="search" onSubmit={event=>{event.preventDefault();window.clearTimeout(searchTimer.current);updateLocation(query);void search(query)}}><label htmlFor="session-search">Search your messages</label><div><input id="session-search" aria-label="Search your messages" type="search" autoComplete="off" value={query} onChange={event=>setQuery(event.target.value)} placeholder="What did you ask Codex to do?"/><button disabled={pending}>{pending?'Searching…':'Search'}</button></div><small>Searches messages you sent in root sessions · exact session IDs also work</small></form>
    <div className="discovery-status" role="status" aria-live="polite">{pending?<><LoaderCircle aria-hidden="true"/>Searching user messages…</>:result?<>{result.coverage.eligible} root session{result.coverage.eligible===1?'':'s'} in indexed snapshot {result.appliedRevision}</>:null}</div>
    {error&&!pending?<div className="error"><h2>Discovery unavailable</h2><p>{error}</p></div>:pending||!result?<div className="discovery-skeleton" aria-label="Search results pending" aria-busy="true">{[0,1,2].map(item=><div key={item}><i/><i/><i/></div>)}</div>:<div className="discovery-results" aria-busy="false">
      {result.items.map(item=>{const duration=sessionDuration(item),total=item.directTokens!=null&&item.descendantTokens!=null?item.directTokens+item.descendantTokens:null;return <a className="discovery-result" key={item.sessionId} href={inspectorPath(`/context/${encodeURIComponent(item.sessionId)}`,{q:appliedQuery||undefined})}><div className="result-main"><h3>{sessionTitle(item)}</h3><p className="result-project">{item.project||<span>Project unavailable</span>}</p><p className="result-meta">{item.startedAt?<time dateTime={item.startedAt}>{new Date(item.startedAt).toLocaleString(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}</time>:'Date unavailable'}{duration&&<> · {duration}</>} · {item.completedTurns} completed turn{item.completedTurns===1?'':'s'} · {item.descendantSessions} spawned</p><code>{item.rawSessionId}</code>{item.matchCategories.map(category=><span className="match-category" key={category}>{matchLabel(category)}</span>)}{item.matchSnippets.slice(0,2).map((snippet,index)=><blockquote className="match-snippet" key={`${snippet.category}-${index}`}><span>{matchLabel(snippet.category)}</span><p><Highlight text={snippet.text} query={appliedQuery}/></p></blockquote>)}</div><dl><dt>Total</dt><dd>{tokens(total)}</dd><dt>Root</dt><dd>{tokens(item.directTokens)}</dd><dt>Descendants</dt><dd>{tokens(item.descendantTokens)}</dd></dl><span className="open-result" aria-hidden="true">Open context <ArrowRight/></span></a>})}
      {result.unavailableExactMatches?.map(item=><article className="unavailable-session-match" key={`${item.rawSessionId}:${item.state}:${item.reason}`}><div><span className="unavailable-badge">Exact raw session ID found</span><h2>Session context is unavailable</h2><code>{item.rawSessionId}</code><p>Inspector found this Codex session by its raw ID, but its rollout was excluded from the indexed session view.</p></div><dl><dt>Status</dt><dd>{item.state.replaceAll('_',' ')}</dd><dt>Codex</dt><dd>{item.detectedVersion}</dd><dt>Reason</dt><dd><code>{item.reason}</code></dd></dl></article>)}
      {result.nextCursor&&<button className="load-more" onClick={()=>void loadMore()}>Load more sessions</button>}
      {result.items.length===0&&!result.unavailableExactMatches?.length&&<div className="empty"><h2>No matching completed sessions</h2><p>Try different words from a message you sent, or paste an exact session ID.</p></div>}
    </div>}
  </section>
}

function SessionView({route,revision}:{route:Route;revision:number}){
  const [map,setMap]=React.useState<SessionMap|null>(null),[summary,setSummary]=React.useState<SessionPage['items'][number]|null>(null),[ledger,setLedger]=React.useState<LedgerPage|null>(null),[error,setError]=React.useState(''),[collapsed,setCollapsed]=React.useState<Set<string>>(new Set()),[scale,setScale]=React.useState(1),[pan,setPan]=React.useState({x:0,y:0}),[drag,setDrag]=React.useState<{x:number;y:number;px:number;py:number}|null>(null),[mapExpanded,setMapExpanded]=React.useState(!route.turnId)
  React.useEffect(()=>{let live=true;setError('');setSummary(null);fetchSessionMap(route.sessionId!,revision).then(value=>{if(!live)return;setMap(value);void fetchSessionMetadata([value.rootSessionId],revision).then(page=>{if(live)setSummary(page.items[0]||null)}).catch(()=>{/* Stable opaque identity remains available. */})}).catch(e=>{if(live)setError((e as Error).message)});return()=>{live=false}},[route.sessionId,revision])
  React.useEffect(()=>{let live=true;if(!route.turnId||!map){setLedger(null);return}void (async()=>{try{let page=await fetchLedger(map.rootSessionId,route.turnId!,revision);const items=[...page.items];let cursor=page.nextCursor;while(cursor&&items.length<10000){page=await fetchLedger(map.rootSessionId,route.turnId!,revision,cursor);items.push(...page.items);cursor=page.nextCursor}if(live)setLedger({...page,items,nextCursor:cursor})}catch(e){if(live){setLedger(null);setError((e as Error).message)}}})();return()=>{live=false}},[map,route.turnId,revision])
  if(error&&!map)return <section className="error"><h2>Session unavailable at this snapshot</h2><p>{error}</p><button onClick={()=>navigate(inspectorPath('/context'))}>Return to discovery</button></section>
  if(!map)return <p className="loading">Building the causal view from normalized facts…</p>
  type Turn=SessionMap['turns'][number]
  type Relation={parentSessionId:string;childSessionId:string;spawnTurnId:string;edgeKind:string;ordinal:number}
  const root=map.nodes.find(node=>node.kind==='root'),turns=map.turns||[],selectedTurn=turns.find(turn=>turn.turnId===route.turnId)
  const nodeBySession=new Map(map.nodes.map(node=>[node.sessionId,node]))
  const turnsBySession=new Map<string,Turn[]>()
  for(const turn of turns){const list=turnsBySession.get(turn.sessionId)||[];list.push(turn);turnsBySession.set(turn.sessionId,list)}
  for(const list of turnsBySession.values())list.sort((a,b)=>a.ordinal-b.ordinal)
  const relations:Relation[]=map.spawnTopology.map(item=>({...item}))
  for(const node of map.nodes){if(node.sessionId===map.rootSessionId||relations.some(item=>item.childSessionId===node.sessionId))continue;const edge=map.edges.find(item=>item.childSessionId===node.sessionId&&item.kind!=='forked_from');if(edge)relations.push({parentSessionId:edge.parentSessionId,childSessionId:node.sessionId,spawnTurnId:node.spawningTurnId||'',edgeKind:edge.kind,ordinal:relations.length})}
  const maxTurnTokens=Math.max(1,...turns.map(turn=>turn.inclusiveTokens||turn.directTokens||0))
  const turnWidth=(turn:Turn)=>Math.max(132,Math.min(520,132+Math.round((turn.inclusiveTokens||turn.directTokens||0)/maxTurnTokens*388)))
  const turnName=(turn:Turn)=>`${turn.sessionKind==='root'?'Turn':'Agent turn'} ${turn.ordinal+1}`
  const selectTurn=(turn:Turn)=>{setMapExpanded(false);navigate(inspectorPath(`/context/${encodeURIComponent(map.rootSessionId)}/turn/${encodeURIComponent(turn.turnId)}`))}
  const fitSession=()=>{setScale(Math.max(.55,Math.min(1,8/Math.max(8,turns.length))));setPan({x:0,y:0})}
  const fitSelection=()=>{setScale(1.12);setPan({x:0,y:0})}
  const resetZoom=()=>{setScale(1);setPan({x:0,y:0})}
  const TurnCard=({turn}:{turn:Turn})=>{const inclusive=turn.inclusiveTokens||turn.directTokens||0,direct=turn.directTokens||0,directPercent=inclusive?Math.max(6,Math.min(100,Math.round(direct/inclusive*100))):0;return <button type="button" className={`turn-map-node ${turn.sessionKind}${turn.turnId===route.turnId?' selected':''}`} style={{width:turnWidth(turn)}} aria-pressed={turn.turnId===route.turnId} onPointerDown={event=>event.stopPropagation()} onClick={()=>selectTurn(turn)}><span className="turn-direct-fill" style={{width:`${directPercent}%`}} aria-hidden="true"/><span className="turn-node-content"><span><strong>{turnName(turn)}</strong><small>{kindLabel(turn.state)} · {new Date(turn.startedAt).toLocaleTimeString()}</small><span className="turn-token-line">{tokens(turn.directTokens)} direct · {tokens(turn.inclusiveTokens)} downstream</span></span><span className="turn-badges"><i>{turn.toolCount} tool{turn.toolCount===1?'':'s'}</i>{turn.errorCount>0&&<i className="error-badge">{turn.errorCount} error{turn.errorCount===1?'':'s'}</i>}{turn.compactionCount>0&&<i className="compaction-badge">{turn.compactionCount} compaction{turn.compactionCount===1?'':'s'}</i>}</span></span></button>}
  const renderBranches=(parentSessionId:string,depth=0,path=new Set<string>()):React.ReactNode=>relations.filter(item=>item.parentSessionId===parentSessionId).sort((a,b)=>a.ordinal-b.ordinal).map(relation=>{if(path.has(relation.childSessionId))return null;const childTurns=turnsBySession.get(relation.childSessionId)||[],spawnTurn=(turnsBySession.get(parentSessionId)||[]).find(turn=>turn.turnId===relation.spawnTurnId),node=nodeBySession.get(relation.childSessionId),nextPath=new Set(path).add(relation.childSessionId),isCollapsed=collapsed.has(relation.childSessionId),offset=depth?28:Math.min(420,32+(spawnTurn?.ordinal||0)*76);return <section className={`agent-turn-branch${isCollapsed?' collapsed':''}`} style={{'--branch-offset':`${offset}px`} as React.CSSProperties} key={`${relation.parentSessionId}:${relation.childSessionId}:${relation.edgeKind}`}><header><span>↳ {spawnTurn?`Spawned by ${turnName(spawnTurn)}`:'Attached descendant'} · <b>{relation.childSessionId}</b> · {tokens(node?.inclusiveTokens)} downstream</span><button type="button" aria-expanded={!isCollapsed} onPointerDown={event=>event.stopPropagation()} onClick={()=>setCollapsed(value=>{const next=new Set(value);if(next.has(relation.childSessionId))next.delete(relation.childSessionId);else next.add(relation.childSessionId);return next})}>{isCollapsed?'Expand branch':'Collapse branch'}</button></header>{!isCollapsed&&<div className="agent-branch-body"><div className="turn-map-lane">{childTurns.map(turn=><TurnCard turn={turn} key={turn.turnId}/>)}</div>{renderBranches(relation.childSessionId,depth+1,nextPath)}</div>}</section>})
  const title=summary?sessionTitle(summary):map.rootSessionId
  return <section className="session-view"><div className="inspector-breadcrumb"><button onClick={()=>navigate(inspectorPath('/context'))}>Discovery</button><span>/</span><button className="root-crumb" onClick={()=>setMapExpanded(true)}>{title}</button>{route.turnId&&<><span>/</span><span aria-current="page">{selectedTurn?turnName(selectedTurn):route.turnId}</span></>}<a className="quiet-link" href={`/reviews/new?session=${encodeURIComponent(map.rootSessionId)}`}>Review effectiveness</a></div>
    <div className="session-identity"><span className="section-label">ROOT SESSION</span><h2>{title}</h2><p>{summary?.project||'Project unavailable'} · {summary?.startedAt?new Date(summary.startedAt).toLocaleString():'Start unavailable'} · {summary?.completedTurns??map.rootTurns.length} completed turns</p></div>
    {map.coverage.fidelity!=='exact'&&<div className="warning"><strong>Partial lineage</strong><p>{map.coverage.reason||'Some causal relationships remain unresolved.'}</p></div>}
    {mapExpanded&&<><div className="map-toolbar"><div><span className="section-label">BIRD'S-EYE VIEW</span><strong>Causal token map</strong><small>Solid area is direct model usage. Each turn boundary includes downstream agent work.</small></div><div><button onClick={fitSession}>Fit session</button><button onClick={fitSelection} disabled={!selectedTurn}>Fit selection</button><button onClick={resetZoom}>Reset zoom</button><output>{Math.round(scale*100)}%</output></div></div>
    <div className="turn-map-legend" aria-label="Causal token map legend"><span><i className="root-key"/>Root turn</span><span><i className="agent-key"/>Spawned-agent turn</span><span><i className="direct-key"/>Direct inside downstream total</span><span><i className="compaction-key"/>Compaction badge</span></div>
    <div className="map-stage" onWheel={event=>{event.preventDefault();setScale(value=>Math.max(.5,Math.min(1.8,value+(event.deltaY<0?.1:-.1))))}} onPointerDown={event=>setDrag({x:pan.x,y:pan.y,px:event.clientX,py:event.clientY})} onPointerMove={event=>{if(drag)setPan({x:drag.x+event.clientX-drag.px,y:drag.y+event.clientY-drag.py})}} onPointerUp={()=>setDrag(null)} onPointerLeave={()=>setDrag(null)}>
      <div className="map-canvas turn-map-canvas" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${scale})`}}><div className="map-root-label"><strong>Root session · {title}</strong><span>{tokens(root?.inclusiveTokens)} inclusive</span></div><div className="turn-map-lane root-lane">{(turnsBySession.get(map.rootSessionId)||[]).map(turn=><TurnCard turn={turn} key={turn.turnId}/>)}</div>{renderBranches(map.rootSessionId)}</div>
      <div className="minimap turn-minimap" aria-label="Causal map minimap">{turns.map(turn=><i className={`${turn.sessionKind}${turn.turnId===route.turnId?' selected':''}`} key={turn.turnId} style={{flex:Math.max(1,Math.round(turnWidth(turn)/70))}}/>)}<span style={{transform:`translate(${-pan.x/18}px,${-pan.y/18}px) scale(${1/scale})`}}/></div>
    </div></>}
    {route.turnId&&!mapExpanded&&<div className="topology-rail"><div><span className="section-label">SESSION TOPOLOGY</span><strong>{selectedTurn?turnName(selectedTurn):'Selected turn'}</strong><small>{selectedTurn?`${tokens(selectedTurn.directTokens)} direct · ${tokens(selectedTurn.inclusiveTokens)} downstream`:'Persistent root and spawned-agent turns'}</small><button className="expand-session-map" onClick={()=>setMapExpanded(true)}>Expand session map</button></div><nav aria-label="Select another recorded turn">{turns.map(turn=><button className={`${turn.sessionKind}${turn.turnId===route.turnId?' selected':''}`} style={{flex:Math.max(1,Math.round(turnWidth(turn)/70))}} aria-pressed={turn.turnId===route.turnId} key={turn.turnId} onClick={()=>selectTurn(turn)}><span>{turnName(turn)}</span><small>{tokens(turn.inclusiveTokens)}</small></button>)}</nav></div>}
    {route.turnId?<TurnInspector rootId={map.rootSessionId} turnId={route.turnId} eventId={route.eventId} evidenceId={route.evidenceId} revision={revision} ledger={ledger}/>:<div className="focus-empty"><h2>Select a recorded turn</h2><p>The full causal topology stays visible while its chronological source evidence opens below.</p><p><span className="derived-badge">Derived aggregate</span> Root {tokens(root?.directTokens)} direct · {tokens(root?.inclusiveTokens)} inclusive tokens. No per-component estimates.</p></div>}
  </section>
}

function TurnInspector({rootId,turnId,eventId,evidenceId,revision,ledger}:{rootId:string;turnId:string;eventId?:string;evidenceId?:string;revision:number;ledger:LedgerPage|null}){
  const selected=ledger?.items.find(item=>item.eventId===eventId||item.evidenceId===evidenceId)
  const activeEvidence=evidenceId||selected?.evidenceId
  const [chunks,setChunks]=React.useState<EvidenceChunk[]>([]),[context,setContext]=React.useState<RecordedContext|null>(null),[error,setError]=React.useState('')
  const eventRef=React.useRef<HTMLElement|null>(null)
  React.useEffect(()=>{eventRef.current?.scrollIntoView?.({block:'nearest',behavior:'smooth'})},[selected?.eventId,ledger])
  React.useEffect(()=>{let live=true;setChunks([]);setContext(null);setError('');if(!activeEvidence)return;Promise.all([fetchEvidence(activeEvidence,revision),fetchRecordedContext(activeEvidence,revision)]).then(([chunk,recorded])=>{if(live){setChunks([chunk]);setContext(recorded)}}).catch(e=>{if(live)setError((e as Error).message)});return()=>{live=false}},[activeEvidence,revision])
  if(!ledger)return <p className="loading">Loading the completed-turn ledger…</p>
  const current=chunks.at(-1),raw=chunks.map(chunk=>chunk.text||'').join('')
  return <div className="turn-focus"><section className="ledger"><div><span className="section-label">CHRONOLOGICAL EVENT LEDGER</span><h2>Full recorded turn</h2><p>{ledger.items.length} source-backed events. Select one to inspect its exact record.</p></div><ol>{ledger.items.map((item,index)=>{const active=item.eventId===selected?.eventId;return <li key={item.eventId}><article ref={active?eventRef:undefined} className={active?'selected':''}><button aria-current={active?'true':undefined} onClick={()=>navigate(inspectorPath(`/context/${encodeURIComponent(rootId)}/turn/${encodeURIComponent(turnId)}/event/${encodeURIComponent(item.eventId)}`,{evidence:item.evidenceId}))}><span>{String(index+1).padStart(2,'0')}</span><strong>{kindLabel(item.kind)}</strong><time>{new Date(item.observedAt).toLocaleTimeString()}</time></button>{(item.kind==='compacted'||item.kind==='context_compacted')&&<small>First-class exact recorded compaction event; surrounding ledger usage remains visible.</small>}</article></li>})}</ol></section>
    <section className="evidence-panel"><span className="section-label">EVENT EVIDENCE</span>{!activeEvidence?<><h2>Choose an event</h2><p>Its opaque evidence reference will resolve against the original source file.</p></>:error?<div className="error"><h2>Evidence unavailable</h2><p>{error}</p></div>:!current?<p className="loading">Verifying pinned source fingerprints…</p>:<><div className="evidence-heading"><div><h2>{selected?kindLabel(selected.kind):'Deep-linked event'}</h2><p>Opaque evidence ID · revision {revision}</p></div><span className={current.availability==='available'?'exact-badge':'unavailable-badge'}>{current.availability==='available'?'Exact source':'Unavailable'}</span></div>
      {current.availability!=='available'?<div className="unavailable-context"><strong>Exact payload unavailable</strong><p>The source is {current.availability.replaceAll('_',' ')}. Indexed metrics and normalized facts remain visible.</p></div>:<><EvidenceView kind={selected?.kind||'record'} observedAt={selected?.observedAt||current.availabilityObservedAt} raw={raw}/><details className="original-record"><summary>View original record</summary><div className="local-evidence-notice"><strong>Displays the original local Codex record</strong><p>It may contain secrets, messages, tool arguments, or results. It is rendered as inert text and never sent elsewhere.</p></div><pre className="raw-evidence" aria-label="Exact inert source payload">{raw}</pre><p className="chunk-meta">{current.encoding==='escaped-bytes'?'Unsafe/control bytes are visibly escaped; nothing is executed.':'UTF-8 source bytes rendered as inert text.'} {chunks.reduce((sum,chunk)=>sum+chunk.bytes,0)} bytes shown.</p>{!current.complete&&<button onClick={()=>void fetchEvidence(activeEvidence,revision,current.offset+current.bytes).then(chunk=>setChunks(value=>[...value,chunk]))}>Load next bounded chunk</button>}</details></>}
      <div className={context?.fidelity==='exact'?'exact-context':'unavailable-context'}><strong>{context?.blocks[0]?.kind==='compaction'?'Exact recorded compaction evidence':context?.fidelity==='exact'?'Context seen by Codex':'Unavailable in demo'}</strong><p>{context?.reason||'The supported source proves this exact recorded model-input boundary.'}</p>{context?.blocks[0]?.kind==='compaction'&&<small>No reconstructed before/after context, preserved/removed classification, or component token estimate is claimed.</small>}</div></>}
    </section>
  </div>
}
