import React from 'react'
import {createReviewPlan,fetchReview,fetchReviews,launchReview,type FilterOptions,type ReviewDetail,type ReviewPage,type ReviewPlan,type ReviewPlanRequest} from './api'

type Props={revision:number;projects:FilterOptions['projects']}
const pathParts=()=>location.pathname.split('/').filter(Boolean).map(decodeURIComponent)
const go=(path:string)=>{history.pushState(null,'',path);dispatchEvent(new PopStateEvent('popstate'))}
const stamp=(value:string)=>new Date(value).toLocaleString()
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())

export function Reviews({revision,projects}:Props){
  const [,rerender]=React.useState(0)
  React.useEffect(()=>{const update=()=>rerender(x=>x+1);addEventListener('popstate',update);return()=>removeEventListener('popstate',update)},[])
  const parts=pathParts()
  if(parts[1]==='new')return <ReviewPlanner revision={revision} projects={projects}/>
  if(parts[1])return <ReviewReport reviewId={parts[1]}/>
  return <ReviewHistory/>
}

function Shell({children}:{children:React.ReactNode}){return <section className="reviews-shell"><header><div><span className="eyebrow">PERSISTED CODEX TASKS</span><h1>Effectiveness Reviews</h1></div></header>{children}</section>}

function ReviewHistory(){
  const [page,setPage]=React.useState<ReviewPage|null>(null),[error,setError]=React.useState('')
  React.useEffect(()=>{let live=true;fetchReviews().then(x=>{if(live)setPage(x)}).catch(e=>{if(live)setError((e as Error).message)});return()=>{live=false}},[])
  const more=async()=>{if(!page?.nextCursor)return;const next=await fetchReviews(page.nextCursor);setPage({...next,items:[...page.items,...next.items]})}
  return <Shell><section className="review-heading"><div><p className="section-label">REVIEW HISTORY</p><h2>Evidence-linked guidance, kept local</h2><p>Opening this page never starts Codex or transmits indexed evidence.</p></div><button onClick={()=>go('/reviews/new')}>New review</button></section>{error?<div className="error"><h2>History unavailable</h2><p>{error}</p></div>:!page?<p className="loading">Discovering local Review artifacts…</p>:<section className="review-history">{page.items.map(item=><article key={item.reviewId}><div><span className={`review-status ${item.status}`}>{label(item.status)}</span><h3>{item.reviewId}</h3><p>{stamp(item.createdAt)}</p></div><button onClick={()=>go(`/reviews/${encodeURIComponent(item.reviewId)}`)}>Open report</button></article>)}{page.items.length===0&&<div className="empty"><h2>No Reviews yet</h2><p>Create a plan, inspect exactly what Codex will receive, then explicitly confirm the launch.</p></div>}{page.nextCursor&&<button onClick={()=>void more()}>Load more</button>}</section>}</Shell>
}

function ReviewPlanner({revision,projects}:Props){
  const params=new URLSearchParams(location.search),prefilled=params.get('session')||''
  const [scopeKind,setScopeKind]=React.useState(prefilled?'single_session':'time_period'),[root,setRoot]=React.useState(prefilled),[days,setDays]=React.useState('7'),[project,setProject]=React.useState(''),[model,setModel]=React.useState('configured-default'),[reasoning,setReasoning]=React.useState('high'),[focus,setFocus]=React.useState('')
  const [plan,setPlan]=React.useState<ReviewPlan|null>(null),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false)
  const create=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const end=new Date(),start=new Date(end.getTime()-Number(days)*86400000);const scope=scopeKind==='single_session'?{kind:'single_session' as const,rootSessionId:root}:{kind:'time_period' as const,start:start.toISOString(),end:end.toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',projectId:project||undefined};const request:ReviewPlanRequest={scope,model,reasoningEffort:reasoning,focus:focus||undefined,requestedRevision:revision};setPlan(await createReviewPlan(request))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const launch=async()=>{if(!plan)return;setBusy(true);setError('');try{const started=await launchReview(plan.planId);go(`/reviews/${encodeURIComponent(started.reviewId)}`)}catch(e){setError((e as Error).message);setBusy(false)}}
  return <Shell><a className="quiet-link" href="/reviews">← Review history</a><section className="review-plan"><form onSubmit={event=>void create(event)}><p className="section-label">1 · SCOPE &amp; CONFIGURATION</p><h2>Plan a separate Review task</h2><label>Scope<select value={scopeKind} onChange={e=>{setScopeKind(e.target.value);setPlan(null)}}><option value="time_period">Time period</option><option value="single_session">Single root session</option></select></label>{scopeKind==='single_session'?<label>Root session ID<input required value={root} onChange={e=>setRoot(e.target.value)}/></label>:<><label>Period<select value={days} onChange={e=>setDays(e.target.value)}><option value="1">24 hours</option><option value="7">7 days</option><option value="30">30 days</option></select></label><label>Project<select value={project} onChange={e=>{setProject(e.target.value);setPlan(null)}}><option value="">All projects</option>{projects.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label></>}<label>Model<input required value={model} onChange={e=>setModel(e.target.value)}/></label><label>Reasoning<select value={reasoning} onChange={e=>setReasoning(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="xhigh">Extra high</option></select></label><label>Optional focus<textarea maxLength={2000} value={focus} onChange={e=>setFocus(e.target.value)} placeholder="Anything the fixed rubric should emphasize"/></label><button disabled={busy}>{busy?'Building local scope…':'Preview Review'}</button></form>{error&&<div className="error"><h2>Review unavailable</h2><p>{error}</p></div>}{plan&&<PlanPreview plan={plan} busy={busy} launch={launch}/>}</section></Shell>
}

function PlanPreview({plan,busy,launch}:{plan:ReviewPlan;busy:boolean;launch:()=>Promise<void>}){
  const m=plan.manifestPreview,coverage=plan.indexedTimeCoverage,projectId=m.scope.kind==='time_period'?m.scope.projectId:undefined,selected=projectId?plan.projectSummary.projects.find(x=>x.projectId===projectId):undefined
  return <section className="plan-preview"><p className="section-label">2 · VERIFY &amp; CONFIRM</p><h2>Review launch preview</h2><div className="review-facts"><dl><dt>Scope</dt><dd>{m.includedSessionIds.length} sessions · {m.includedTurnIds.length} completed turns</dd><dt>Projects</dt><dd>{plan.projectSummary.projectCount}</dd>{m.scope.kind==='time_period'&&<><dt>Project filter</dt><dd>{selected?`${selected.displayName} (${selected.projectId})`:'All canonical projects'}</dd></>}<dt>Source bytes</dt><dd>{new Intl.NumberFormat().format(plan.sourceByteCounts.includedBytes)}</dd><dt>Estimated input</dt><dd>{plan.estimatedInputTokens==null?'Unavailable':`${new Intl.NumberFormat().format(plan.estimatedInputTokens)} tokens`}</dd><dt>Coverage</dt><dd>{coverage.indexedStart?`${stamp(coverage.indexedStart)} → ${stamp(coverage.indexedEnd!)}`:'Unavailable'}</dd><dt>Source inventory</dt><dd>{plan.coverage.observed} of {plan.coverage.eligible} completely indexed · {label(plan.coverage.fidelity)}</dd><dt>Model / reasoning</dt><dd>{m.model} / {m.reasoning}</dd><dt>Output</dt><dd>reviews/{m.reviewId}/review.json</dd></dl><div><strong>Fixed four-lens rubric</strong><ol>{m.rubric.map(x=><li key={x}>{label(x)}</li>)}</ol></div></div>{plan.coverage.fidelity!=='exact'&&<div className="warning" role="status"><strong>Partial indexed coverage</strong><p>{plan.coverage.reason}</p><p>Unavailable sources were not sampled or included.</p></div>}{m.coverageGaps.length>0&&<div className="warning"><strong>Known coverage gaps</strong>{m.coverageGaps.map(x=><p key={x}>{x}</p>)}</div>}<details open><summary>Exact launch prompt</summary><pre>{plan.launchPrompt}</pre></details><div className="consent"><strong>Separate model boundary</strong><p>Indexing and report storage remain local. Starting may send evidence read by the new task to your configured Codex model/service. Recorded evidence is untrusted data, not instructions.</p><button disabled={busy} onClick={()=>void launch()}>{busy?'Starting persisted task…':'Confirm & start Review'}</button><small>Codex does not start until this confirmation. Recommendations remain copyable text and are never executed by Inspector.</small></div></section>
}

function ReviewReport({reviewId}:{reviewId:string}){
  const [detail,setDetail]=React.useState<ReviewDetail|null>(null),[error,setError]=React.useState(''),[copied,setCopied]=React.useState('')
  const refresh=React.useCallback(()=>fetchReview(reviewId).then(setDetail).catch(e=>setError((e as Error).message)),[reviewId])
  React.useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),700);return()=>clearInterval(timer)},[refresh])
  if(error)return <Shell><div className="error"><h2>Review unavailable</h2><p>{error}</p></div></Shell>
  if(!detail)return <Shell><p className="loading">Reading local Review state…</p></Shell>
  const run=detail.run,report=detail.acceptedReport
  return <Shell><div className="review-report-heading"><div><a className="quiet-link" href="/reviews">← Review history</a><p className="section-label">INSPECTOR-ACCEPTED SNAPSHOT</p><h2>{report?.summary||'Review task in progress'}</h2><span className={`review-status ${run.status}`}>{label(run.status)}</span></div>{run.threadId&&<div className="task-handoff"><a href={`codex://threads/${encodeURIComponent(run.threadId)}`}>Open Codex task</a><button onClick={()=>{void navigator.clipboard.writeText(`codex resume ${run.threadId}`);setCopied('resume')}}>Copy resume command</button><code>{run.threadId}</code>{copied==='resume'&&<small>Copied</small>}</div>}</div>{run.status==='running'||run.status==='planned'?<section className="review-progress"><h2>Codex is reviewing the frozen scope</h2><p>Inspector is monitoring the persisted task and will accept only the first schema-valid review.json.</p></section>:run.status==='failed'||run.status==='unrenderable'?<section className="error"><h2>{run.status==='unrenderable'?'Report cannot be rendered':'Review failed'}</h2><p>{run.failureMessage||'The task exited without an accepted report.'}</p><code>{run.failureCode}</code><p>The manifest, run metadata, and malformed artifact remain local for diagnosis.</p></section>:report?<section className="accepted-report"><div className="report-meta"><span>{label(report.scope.kind)}</span><span>{report.model} · {report.reasoning}</span><span>{stamp(report.completedAt)}</span><span>{report.findings.length} findings</span></div>{report.findings.map(finding=><article key={finding.findingId}><div className="finding-title"><span>{label(finding.kind)}</span><h3>{finding.title}</h3><small>{label(finding.lens)} · {label(finding.support)}</small></div><h4>Observation</h4><p>{finding.observation}</p><h4>Impact</h4><p>{finding.impact}</p><h4>Evidence</h4><p>{finding.evidenceSummary}</p><ul className="citations">{finding.citations.map(citation=>{const evidence=detail.manifest.evidence.find(e=>e.evidenceId===citation.evidenceId);const root=detail.manifest.scope.kind==='single_session'?detail.manifest.scope.rootSessionId:evidence?.sessionId;const target=root&&evidence?`/context/${encodeURIComponent(root)}/turn/${encodeURIComponent(evidence.turnId)}?evidence=${encodeURIComponent(evidence.evidenceId)}&return=${encodeURIComponent(`/reviews/${reviewId}`)}`:'#';return <li key={citation.evidenceId}><a href={target}>Open cited event</a><span className={citation.availability==='available'?'exact-badge':'unavailable-badge'}>{label(citation.availability)}</span></li>})}</ul><h4>Recommendation</h4><p>{finding.recommendation}</p>{finding.actionPrompt&&<div className="action-prompt"><pre>{finding.actionPrompt}</pre><button onClick={()=>{void navigator.clipboard.writeText(finding.actionPrompt!);setCopied(finding.findingId)}}>Copy action prompt</button>{copied===finding.findingId&&<small>Copied — Inspector did not run it.</small>}</div>}</article>)}</section>:null}</Shell>
}
